### ISSUE TITLE
Clash配置文件  里面节点不全

### ISSUE THREAD

**Issue by feimeng2017** [Devmiston/sing-box#1]
配置了Hysteria2       TUIC     VLESS+Vision+REALITY      VMess+WebSocket+TLS       只有   VLESS+Vision+REALITY这一个节点     singbox配置文件里面是全的

**Comment by Devmiston** [comment]
等我抽个时间把Clash的配置再整合一下，之前只是把sing-box的配置整合了一下

**Comment by feimeng2017** [comment]
好的  大佬辛苦

**Comment by Devmiston** [comment]
你是不是开启了ECH？

**Comment by feimeng2017** [comment]
尝试了一下不开启ECH之后  确实可以了   辛苦大佬

**Comment by beautygirl1998** [comment]
@smith-stack 大佬，请问可以增加splithttp协议吗？
